build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "HomeNetwork for Hillstate"
  org.opencontainers.image.description: "RS-485 based homenetwork application for hillstate (hyundai ht)"
  org.opencontainers.image.source: "https://github.com/YOGYUI/homeassistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
