name: HomeNetwork for Hillstate
version: "1.0.9"
slug: yogyui_homenet_hillstate
description: RS-485 based HomeNetwork for Hillstate (Hyundai HT)
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: yogyui/ha-addon-{arch}-homenet-hillstate
init: false
startup: application
url: https://github.com/YOGYUI/homeassistant-addons/tree/main/homenet-hillstate
ingress: true
ingress_port: 7929
ingress_entry: /
ingress_stream: false
full_access: false
apparmor: true
uart: true
usb: true
gpio: true
panel_icon: mdi:home-automation
panel_title: YOGYUI-HILLSTATE
panel_admin: false
map:
  - addon_config:rw
  - share:rw
  - backup:rw
options:
  app_config_file_path: /config/app_config.xml
  mqtt_broker:
    host: core-mosquitto
    port: 1883
    username: username
    password: password
    client_id: yogyui_hyundai_ht
    tls_enable: false
    tls_ca_certs: /config/ssl/cacert.pem
    tls_certfile: /config/ssl/fullchain.pem
    tls_keyfile: /config/ssl/privkey.pem
  rs485:
    - name: port1
      index: 0
      enable: true
      hwtype: 0
      packettype: 0
      serial: /dev/ttyUSB0
      baudrate: 9600
      databit: 8
      parity: N
      stopbits: 1
      socketaddr: 127.0.0.1
      socketport: 8899
  discovery:
    activate: false
    prefix: homeassistant
    timeout: 60
  parser_mapping:
    light: 0
    outlet: 0
    gasvalve: 0
    thermostat: 0
    ventilator: 0
    airconditioner: 0
    elevator: 0
    subphone: 0
    batchoffsw: 0
    hems: 0
    emotionlight: 0
  periodic_query_state:
    enable: false
    period: 1000
    verbose: false
  etc: 
    thermo_len_per_dev: 3
    thermostat_range_min: 18
    thermostat_range_max: 35
    airconditioner_range_min: 18
    airconditioner_range_max: 35
    elevator_packet_call_type: 0
    elevator_check_command_method: 0
    clear_all_devices: false
schema:
  app_config_file_path: str
  mqtt_broker:
    host: str
    port: int
    username: str
    password: str
    client_id: str
    tls_enable: bool
    tls_ca_certs: str
    tls_certfile: str
    tls_keyfile: str
  rs485:
    - name: str
      index: int(0,)
      enable: bool
      hwtype: int(0,1)
      packettype: int(0,1)
      serial: str
      baudrate: int
      databit: int(5,8)
      parity: str
      stopbits: float
      socketaddr: str
      socketport: int
  discovery:
    activate: bool
    prefix: str
    timeout: int(1,)
  parser_mapping:
    light: int(0,)
    outlet: int(0,)
    gasvalve: int(0,)
    thermostat: int(0,)
    ventilator: int(0,)
    airconditioner: int(0,)
    elevator: int(0,)
    subphone: int(0,)
    batchoffsw: int(0,)
    hems: int(0,)
    emotionlight: int(0,)
  periodic_query_state:
    enable: bool
    period: int
    verbose: bool
  etc:
    thermo_len_per_dev: int(1,)
    thermostat_range_min: int
    thermostat_range_max: int
    airconditioner_range_min: int
    airconditioner_range_max: int
    elevator_packet_call_type: int(0,1)
    elevator_check_command_method: int(0,1)
    clear_all_devices: bool
  