name: HomeNetwork for Hillstate
version: "1.0.1"
slug: yogyui_homenet_hillstate
description: RS-485 based HomeNetwork for Hillstate (Hyundai HT)
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
# image: yogyui/ha-addon-homenet-hillstate
image: yogyui/ha-addon-{arch}-homenet-hillstate
init: false
startup: application
url: https://github.com/YOGYUI/homeassistant-addons/tree/main/homenet-hillstate
ingress: true
ingress_port: 7929
ingress_entry: /
ingress_stream: false
ports:
  7929/tcp: 7929
ports_description:
  7929/tcp: Web service server port
privileged:
  - SYS_ADMIN
full_access: true
apparmor: false
panel_icon: mdi:home-automation
panel_title: YOGYUI-HILLSTATE
panel_admin: false
map:
  - share:rw
